version: '3.8'

services:
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: agent
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882"
    env_file:
      - .env.local
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped
